### ISSUE TITLE
Card layout get wrong size if summary contains a very long word

### ISSUE THREAD

**Issue by lundhgren** [glonlas/AgileStoryPrint#10]
If summary on one story contains a very long word without spaces, the card layout for all cards in the xml get the wrong layout. Please see attached xml input and pdf output.

(Changed file type on input xml to txt to be able to upload)

[SearchRequest.txt](https://github.com/glonlas/Jira2ScrumBoard/files/555387/SearchRequest.txt)
[output.pdf](https://github.com/glonlas/Jira2ScrumBoard/files/555388/output.pdf)

**Comment by glonlas** [comment]
Hi,

Thank you for the report. I will have a look at it.

**Comment by glonlas** [comment]
Hi @lundhgren,

The bug is fixed on the [version v1.2.1](https://github.com/glonlas/Jira2ScrumBoard/releases/tag/v1.2.1) and also on the website [Jira2scrumboard.com](http://www.jira2scrumboard.com/).

**The result:** 
[stories-584e1e42ee1d0.pdf](https://github.com/glonlas/Jira2ScrumBoard/files/645078/stories-584e1e42ee1d0.pdf)

Is it good for you?

Thank you :)
